---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
searchRules:
- keyMatcher:
    name: package
    path: [spec, package]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
 name: provider-azure
spec:
 package: crossplane/provider-azure:v0.19.0
 skipDependencyResolution: true