apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmysqlinstances.database.example.org
spec:
  claimNames:
    kind: MySQLInstance
    plural: mysqlinstances
  connectionSecretKeys:
  - type
  - provider
  - username
  - password
  - host
  - database
  - port
  group: database.example.org
  names:
    kind: XMySQLInstance
    plural: xmysqlinstances
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The OpenAPIV3Schema of this Composite Resource Definition.
            properties:
              parameters:
                properties:
                  size:
                    description: Small - 1 GB storage, Medium - 5 GB storage, Large
                      - 20 GB
                    enum:
                    - small
                    - medium
                    - large
                    type: string
                required:
                - size
                type: object
            required:
            - parameters
            type: object
        type: object
    served: true